export const ADD_ARTICLE = "CONST_ADD_ARTICLE";
export const DELETE_ARTICLE = "CONST_DELETE_ARTICLE";
export const UPDATE_ARTICLE = "CONST_UPDATE_ARTICLE";
export const LIKE_ARTICLE = "CONST_LIKE_ARTICLE"
export const CHANGE_TAB = "CONST_CHANGE_TAB"
