export const READ_ARTICLE_BEGIN   = 'READ_ARTICLE_BEGIN';
export const READ_ARTICLE_SUCCESS = 'READ_ARTICLE_SUCCESS';
export const READ_ARTICLE_FAILURE = 'READ_ARTICLE_FAILURE';
export const DELETE_ARTICLE = "CONST_DELETE_ARTICLE";
export const UPDATE_ARTICLE = "CONST_UPDATE_ARTICLE";
export const LIKE_ARTICLE = "CONST_LIKE_ARTICLE"
export const CHANGE_TAB = "CONST_CHANGE_TAB"
export const LOGIN = 'CONST_LOGIN';